domain: .entur.io
environment: production
loadBalancerIP: 35.205.233.237
config: |-
    [
      {
        "id": "stop-places",
        "name": "stop-places",
        "url": "https://api.entur.io/stop-places/v1/graphql",
        "queries": "stop-places",
        "defaultQuery": "stopPlace"
      },
      {
        "id": "journey-planner",
        "name": "journey-planner-v2",
        "url": "https://api.entur.io/journey-planner/v2/graphql",
        "queries": "journey-planner",
        "defaultQuery": "trip"
      },
      {
        "id": "journey-planner-v3",
        "name": "journey-planner-v3-beta",
        "url": "https://api.dev.entur.io/journey-planner/v3/graphql",
        "queries": "journey-planner",
        "defaultQuery": "trip"
      }
    ]
